version: "3.9"

services:
  robot_devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VSCODE_COMMIT: ${VSCODE_COMMIT}
        NVM_VERSION: ${NVM_VERSION}
        NVM_DIR: ${NVM_DIR}
        NODE_DEFAULT: ${NODE_DEFAULT}
    container_name: robotframework
    working_dir: /robot
    command: sleep infinity
    tty: true
    networks:
      - robot-net  

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - robot-net

networks:
  robot-net:
    driver: bridge